services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                NODE_VERSION: '22'
        container_name: waste-collection-app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            XDEBUG_MODE: 'off'
            XDEBUG_CONFIG: client_host=host.docker.internal
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        depends_on:
            - mysql
            - pgsql
        networks:
            - app-network
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - '8000:80'
        volumes:
            - '.:/var/www/html'
            - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
        depends_on:
            - app
        networks:
            - app-network
    mysql:
        image: mysql/mysql-server:8.0
        container_name: mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: waste-collection
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql-data:/var/lib/mysql'
        networks:
            - app-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - '8081:80'
        environment:
            PMA_HOST: mysql
            PMA_USER: user
            PMA_PASSWORD: password
        depends_on:
            - mysql
        networks:
            - app-network
    pgsql:
        image: postgres:17
        container_name: pgsql
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: waste-collection
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        volumes:
            - 'pgsql-data:/var/lib/postgresql/data'
        networks:
            - app-network
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - '5050:80'
        depends_on:
            - pgsql
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    mysql-data:
    pgsql-data:
